# Generated by Django 2.1.15 on 2021-05-17 17:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communitymanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'communities',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='communaute',
            name='abonnes',
        ),
        migrations.DeleteModel(
            name='Communaute',
        ),
    ]
