# Generated by Django 2.1.15 on 2021-05-18 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0005_auto_20210518_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of creation of the post'),
        ),
    ]
