# Generated by Django 2.1.15 on 2021-05-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0008_auto_20210518_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
