# Generated by Django 2.1.15 on 2021-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0009_auto_20210521_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'ordering': ['name'], 'verbose_name': 'community'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_creation'], 'verbose_name': 'title'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'name'},
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('White', 1), ('Orange', 2), ('Red', 3)], default='White', max_length=50),
        ),
    ]
