# Generated by Django 2.1.15 on 2021-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0010_auto_20210531_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.IntegerField(choices=[(1, 'White'), (2, 'Orange'), (3, 'Red')], default=1),
        ),
    ]
