# Generated by Django 2.1.15 on 2021-06-01 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0014_auto_20210601_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readers',
            field=models.ManyToManyField(related_name='readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
