# Generated by Django 2.1.15 on 2021-06-01 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communitymanager', '0015_auto_20210601_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readers',
            field=models.ManyToManyField(related_name='post_readers', to=settings.AUTH_USER_MODEL),
        ),
    ]
